/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAssessmentsRouteImport } from './routes/admin.assessments'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminLecturesRouteImport } from './routes/admin.lectures'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminSummariesRouteImport } from './routes/admin.summaries'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AssessAssessmentIdRouteImport } from './routes/assess.$assessmentId'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as LecturesLectureIdSummaryRouteImport } from './routes/lectures.$lectureId.summary'
import { Route as LecturesLectureIdSummaryIndexRouteImport } from './routes/lectures.$lectureId.summary.index'
import { Route as LecturesLectureIdSummaryChatThreadIdRouteImport } from './routes/lectures.$lectureId.summary.chat.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssessmentsRoute = AdminAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLecturesRoute = AdminLecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSummariesRoute = AdminSummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => AdminRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessAssessmentIdRoute = AssessAssessmentIdRouteImport.update({
  id: '/assess/$assessmentId',
  path: '/assess/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesLectureIdSummaryRoute =
  LecturesLectureIdSummaryRouteImport.update({
    id: '/lectures/$lectureId/summary',
    path: '/lectures/$lectureId/summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const LecturesLectureIdSummaryIndexRoute =
  LecturesLectureIdSummaryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LecturesLectureIdSummaryRoute,
  } as any)
const LecturesLectureIdSummaryChatThreadIdRoute =
  LecturesLectureIdSummaryChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => LecturesLectureIdSummaryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/lectures': typeof AdminLecturesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/summaries': typeof AdminSummariesRoute
  '/api/chat': typeof ApiChatRoute
  '/assess/$assessmentId': typeof AssessAssessmentIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/lectures/$lectureId/summary': typeof LecturesLectureIdSummaryRouteWithChildren
  '/lectures/$lectureId/summary/': typeof LecturesLectureIdSummaryIndexRoute
  '/lectures/$lectureId/summary/chat/$threadId': typeof LecturesLectureIdSummaryChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/lectures': typeof AdminLecturesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/summaries': typeof AdminSummariesRoute
  '/api/chat': typeof ApiChatRoute
  '/assess/$assessmentId': typeof AssessAssessmentIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/lectures/$lectureId/summary': typeof LecturesLectureIdSummaryIndexRoute
  '/lectures/$lectureId/summary/chat/$threadId': typeof LecturesLectureIdSummaryChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/lectures': typeof AdminLecturesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/summaries': typeof AdminSummariesRoute
  '/api/chat': typeof ApiChatRoute
  '/assess/$assessmentId': typeof AssessAssessmentIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/lectures/$lectureId/summary': typeof LecturesLectureIdSummaryRouteWithChildren
  '/lectures/$lectureId/summary/': typeof LecturesLectureIdSummaryIndexRoute
  '/lectures/$lectureId/summary/chat/$threadId': typeof LecturesLectureIdSummaryChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/progress'
    | '/admin/assessments'
    | '/admin/courses'
    | '/admin/lectures'
    | '/admin/questions'
    | '/admin/summaries'
    | '/api/chat'
    | '/assess/$assessmentId'
    | '/courses/$courseId'
    | '/admin/'
    | '/courses/'
    | '/lectures/$lectureId/summary'
    | '/lectures/$lectureId/summary/'
    | '/lectures/$lectureId/summary/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/progress'
    | '/admin/assessments'
    | '/admin/courses'
    | '/admin/lectures'
    | '/admin/questions'
    | '/admin/summaries'
    | '/api/chat'
    | '/assess/$assessmentId'
    | '/courses/$courseId'
    | '/admin'
    | '/courses'
    | '/lectures/$lectureId/summary'
    | '/lectures/$lectureId/summary/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/progress'
    | '/admin/assessments'
    | '/admin/courses'
    | '/admin/lectures'
    | '/admin/questions'
    | '/admin/summaries'
    | '/api/chat'
    | '/assess/$assessmentId'
    | '/courses/$courseId'
    | '/admin/'
    | '/courses/'
    | '/lectures/$lectureId/summary'
    | '/lectures/$lectureId/summary/'
    | '/lectures/$lectureId/summary/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ApiChatRoute: typeof ApiChatRoute
  AssessAssessmentIdRoute: typeof AssessAssessmentIdRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LecturesLectureIdSummaryRoute: typeof LecturesLectureIdSummaryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessments': {
      id: '/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAssessmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lectures': {
      id: '/admin/lectures'
      path: '/lectures'
      fullPath: '/admin/lectures'
      preLoaderRoute: typeof AdminLecturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/summaries': {
      id: '/admin/summaries'
      path: '/summaries'
      fullPath: '/admin/summaries'
      preLoaderRoute: typeof AdminSummariesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/$assessmentId': {
      id: '/assess/$assessmentId'
      path: '/assess/$assessmentId'
      fullPath: '/assess/$assessmentId'
      preLoaderRoute: typeof AssessAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures/$lectureId/summary': {
      id: '/lectures/$lectureId/summary'
      path: '/lectures/$lectureId/summary'
      fullPath: '/lectures/$lectureId/summary'
      preLoaderRoute: typeof LecturesLectureIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures/$lectureId/summary/': {
      id: '/lectures/$lectureId/summary/'
      path: '/'
      fullPath: '/lectures/$lectureId/summary/'
      preLoaderRoute: typeof LecturesLectureIdSummaryIndexRouteImport
      parentRoute: typeof LecturesLectureIdSummaryRoute
    }
    '/lectures/$lectureId/summary/chat/$threadId': {
      id: '/lectures/$lectureId/summary/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/lectures/$lectureId/summary/chat/$threadId'
      preLoaderRoute: typeof LecturesLectureIdSummaryChatThreadIdRouteImport
      parentRoute: typeof LecturesLectureIdSummaryRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssessmentsRoute: typeof AdminAssessmentsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminLecturesRoute: typeof AdminLecturesRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminSummariesRoute: typeof AdminSummariesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssessmentsRoute: AdminAssessmentsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminLecturesRoute: AdminLecturesRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminSummariesRoute: AdminSummariesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LecturesLectureIdSummaryRouteChildren {
  LecturesLectureIdSummaryIndexRoute: typeof LecturesLectureIdSummaryIndexRoute
  LecturesLectureIdSummaryChatThreadIdRoute: typeof LecturesLectureIdSummaryChatThreadIdRoute
}

const LecturesLectureIdSummaryRouteChildren: LecturesLectureIdSummaryRouteChildren =
  {
    LecturesLectureIdSummaryIndexRoute: LecturesLectureIdSummaryIndexRoute,
    LecturesLectureIdSummaryChatThreadIdRoute:
      LecturesLectureIdSummaryChatThreadIdRoute,
  }

const LecturesLectureIdSummaryRouteWithChildren =
  LecturesLectureIdSummaryRoute._addFileChildren(
    LecturesLectureIdSummaryRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ApiChatRoute: ApiChatRoute,
  AssessAssessmentIdRoute: AssessAssessmentIdRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LecturesLectureIdSummaryRoute: LecturesLectureIdSummaryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
